---
name: ghaction-cmake
description: 'Build and test using cmake'
inputs:
  dependencies:
    description: 'Dependencies as Debian packages to install'
    default: ''
  cc:
    description: 'Compiler'
    default: 'gcc'
  cflags:
    description: 'CFLAGS'
    default: ''
  cxxflags:
    description: 'CXXFLAGS'
    default: ''
  ctestflags:
    description: 'Flags for ctest'
    default: ''
  coverage:
    description: 'Send coverage data to this service (only codecov supported)'
    default: ''
  analyzer:
    description: 'Analyzer to use on files after exporting commands'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
