---
name: ghaction-cmake
description: |
  Swiss army tool for projects based on cmake
branding:
  icon: 'compass'
  color: 'blue'
inputs:
  dependencies_debian:
    description: 'Dependencies as Debian packages to install; always used'
    default: ''
  directory:
    description: 'cd to this directory; always used'
    default: ''
  cmakeflags:
    description: 'Initial flags for cmake; extended by presets'
    default: ''
  build_command:
    description: 'Build command to use; override presets'
    default: ''
  test_command:
    description: 'Test command to use; override presets'
    default: ''
  post_command:
    description: 'Command to run after tests; override presets'
    default: ''
  preset:
    description: |
      Preset to use:
      - cppcheck
      - iwyu
      - clang-tidy
      - clang-sanitize-*
      - valgrind
      - coverage
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
