---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker://lpenz/omnilint:0.5
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-python@v4.3.0
      - name: Install pytest
        run: python -m pip install pytest
      - run: pytest
  test:
    strategy:
        matrix:
          preset:
            - cppcheck
            - install
            - clang-tidy
            - clang-sanitize-address
            - clang-sanitize-memory
            - clang-sanitize-undefined
            - clang-sanitize-dataflow
            - clang-sanitize-safe-stack
            - gcc-sanitize-address
            - valgrind
            - cpack
            - coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          path: ghaction-cmake
      - uses: actions/checkout@v3.1.0
        with:
          repository: lpenz/execpermfix
          path: execpermfix
          fetch-depth: 0
      - uses: ./ghaction-cmake
        with:
          preset: ${{ matrix.preset }}
          working-directory: execpermfix
  publish-dockerhub:
    needs: [ omnilint, test ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          # Default
          - base: debian:bullseye
            platform: 'linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64'
            label: ''
          # Tag each platform:
          - base: debian:bullseye
            platform: linux/386
            label: -386
          - base: debian:bullseye
            platform: linux/amd64
            label: -amd64
          - base: debian:bullseye
            platform: linux/arm/v6
            label: -armv6
          - base: debian:bullseye
            platform: linux/arm/v7
            label: -armv7
          - base: debian:bullseye
            platform: linux/arm64
            label: -arm64
          # Raspbian:
          - base: lpenz/raspbian-buster-armhf
            platform: linux/arm/v7
            label: -raspbian-buster-armhf
          - base: lpenz/raspbian-bullseye-armhf
            platform: linux/arm/v7
            label: -raspbian-bullseye-armhf
    steps:
      - uses: actions/checkout@v3.1.0
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.11.0
      - uses: docker/setup-qemu-action@v2.1.0
      - uses: docker/setup-buildx-action@v2.2.1
      - uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ steps.version.outputs.version_docker_ci != 'null' }}
      - uses: docker/build-push-action@v3.2.0
        with:
          build-args: BASE=${{ matrix.variant.base }}
          push: ${{ steps.version.outputs.version_docker_ci != 'null' }}
          platforms: ${{ matrix.variant.platform }}
          tags: ${{ github.repository }}:${{ steps.version.outputs.version_docker_ci }}${{ matrix.variant.label }}
  publish-github-release:
    needs: [ publish-dockerhub ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.11.0
      - name: publish github release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        if: steps.version.outputs.version_tagged != ''
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
