---
name: CI
on: [ push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://lpenz/omnilint:v0.2
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: Install pytest
        run: python -m pip install pytest
      - run: pytest
  test:
    strategy:
        matrix:
          preset:
            - cppcheck
            - install
            - clang-tidy
            - clang-sanitize-address
            - clang-sanitize-memory
            - clang-sanitize-undefined
            - clang-sanitize-dataflow
            - clang-sanitize-safe-stack
            - gcc-sanitize-address
            - valgrind
            # - cpack fails due to unspecified package version
            - coverage
            - cmake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ghaction-cmake
      - uses: actions/checkout@v2
        with:
          repository: lpenz/execpermfix
          path: execpermfix
          fetch-depth: 0
      - uses: ./ghaction-cmake
        with:
          preset: ${{ matrix.preset }}
          working-directory: execpermfix
  dockerhub:
    needs: [ omnilint, test ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - base: debian:sid
            platform: linux/amd64
            label: main-gstreamer
            gstreamer-commit: d75a69ec951949962ee5a3df3f136452e8712a88
    steps:
      - uses: actions/checkout@v2
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.7
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          build-args: |
            BASE=${{ matrix.variant.base }}
            GSTREAMER_COMMIT_HASH=${{ matrix.variant.gstreamer-commit }}
          push: true
          platforms: ${{ matrix.variant.platform }}
          tags: |
            fractalbasedlifeforms/ghaction-cmake:${{ matrix.variant.label }}
            fractalbasedlifeforms/ghaction-cmake:${{ matrix.variant.label }}-${{ matrix.variant.gstreamer-commit }}
